# Generated by Django 5.1.4 on 2025-03-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_comment_projectrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
